valor = input('Digite um valor: ')
print('Numérico? {}'.format(valor.isnumeric()))
print('Alfa? {}'.format(valor.isalpha()))
print('Alfanumérico? {}'.format(valor.isalnum()))
print('Maisculo? {}'.format(valor.isupper()))
print('Digito? {}'.format(valor.isdigit()))
print('Decimal? {}'.format(valor.isdecimal()))
print('Minusculo? {}'.format(valor.islower()))
print('Espaço? {}'.format(valor.isspace()))