n = input('Digite um valor: ')
print('Numérico? {}'.format(n.isnumeric()))
print('Alfa? {}'.format(n.isalpha()))
print('Alfanumérico? {}'.format(n.isalnum()))
print('Maisculo? {}'.format(n.isupper()))
print('Digito? {}'.format(n.isdigit()))
print('Decimal? {}'.format(n.isdecimal()))
print('Minusculo? {}'.format(n.islower()))
print('Espaço? {}'.format(n.isspace()))
